#!/usr/bin/env bash
# Install the phone fingerprint approval stack:
#   - build + install the approval daemon, helper and PAM module
#   - create the dedicated phonefprint system user, key store and TLS dirs
#   - install + enable the systemd unit (TLS listener on :4443)
#   - wire pam_fingerkey.so into /etc/pam.d/sudo (above @include common-auth)
#
# Idempotent — safe to re-run. Must run as root.
set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then
    echo "error: must run as root (sudo $0)" >&2
    exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

DAEMON_BIN="/usr/local/libexec/fingerkeyd"
PAIR_BIN="/usr/local/bin/fingerkey"
PAM_MODULE="/usr/lib/x86_64-linux-gnu/security/pam_fingerkey.so"
UNIT_SRC="etc/systemd/fingerkeyd.service"
UNIT_DST="/etc/systemd/system/fingerkeyd.service"
KEYS_PARENT="/var/lib/phone-fprint-auth"
KEYS_DIR="/var/lib/phone-fprint-auth/keys"
TLS_DIR="/var/lib/phone-fprint-auth/tls"
DAEMON_USER="phonefprint"
PAM_LINE="auth sufficient pam_fingerkey.so"

# wire_pam_file inserts the approval module line into a PAM service file
# as the FIRST auth line, above @include common-auth. Idempotent.
wire_pam_file() {
    local file="$1"
    local backup

    if grep -q 'pam_fingerkey.so' "${file}"; then
        echo "pam: '${PAM_LINE}' already present in ${file} — skipping"
        return 0
    fi
    backup="${file}.orig-$(date +%s)"
    if [[ ! -e "${backup}" ]]; then
        cp -p "${file}" "${backup}"
        echo "pam: backed up ${file} -> ${backup}"
    fi
    # Insert as the FIRST auth line, above @include common-auth.
    sed -i "/^@include[[:space:]]\\+common-auth\$/i ${PAM_LINE}" "${file}"
    if ! grep -q 'pam_fingerkey.so' "${file}"; then
        echo "error: failed to insert '${PAM_LINE}' into ${file}" >&2
        exit 1
    fi
    echo "pam: inserted '${PAM_LINE}' into ${file}"
}

echo "== build =="
mkdir -p /usr/local/libexec
go build -o "${DAEMON_BIN}" ./daemon
chown root:root "${DAEMON_BIN}"
chmod 0755 "${DAEMON_BIN}"
echo "built ${DAEMON_BIN}"

mkdir -p /usr/local/bin
go build -o "${PAIR_BIN}" ./scripts/fingerkey
chown root:root "${PAIR_BIN}"
chmod 0755 "${PAIR_BIN}"
echo "built ${PAIR_BIN}"

make -C pam
echo "built pam/pam_fingerkey.so"

echo "== system user =="
if id -u "${DAEMON_USER}" &>/dev/null; then
    echo "user ${DAEMON_USER} already exists"
else
    useradd --system --no-create-home --shell /usr/sbin/nologin "${DAEMON_USER}"
    echo "created user ${DAEMON_USER}"
fi

echo "== key store dir =="
install -d -m 0755 "${KEYS_PARENT}"
echo "ensured ${KEYS_PARENT} (0755, traversable by ${DAEMON_USER})"
install -d -o "${DAEMON_USER}" -g "${DAEMON_USER}" -m 0755 "${KEYS_DIR}"
echo "ensured ${KEYS_DIR} (${DAEMON_USER} 0755)"
# Migrate any public keys written with the old 0600 mode (public keys carry
# no secret); the directory itself is handled by install -d above.
find "${KEYS_DIR}" -maxdepth 1 -type f -name '*.pub' -exec chmod 0644 {} + 2>/dev/null || true

echo "== tls dir =="
# The daemon generates cert.pem/key.pem here on first start — the dir
# must exist and be writable by the daemon user.
install -d -o "${DAEMON_USER}" -g "${DAEMON_USER}" -m 0700 "${TLS_DIR}"
echo "ensured ${TLS_DIR} (${DAEMON_USER} 0700)"

echo "== install files =="
install -o root -g root -m 0644 pam/pam_fingerkey.so "${PAM_MODULE}"
install -o root -g root -m 0644 "${UNIT_SRC}" "${UNIT_DST}"
echo "installed ${PAM_MODULE}, ${UNIT_DST}"

echo "== systemd =="
systemctl daemon-reload
systemctl enable --now fingerkeyd
systemctl restart fingerkeyd
echo "enabled + restarted fingerkeyd"

if [[ ! -S /run/phone-fprint-auth/daemon.sock ]]; then
    for _ in $(seq 1 25); do
        [[ -S /run/phone-fprint-auth/daemon.sock ]] && break
        sleep 0.2
    done
fi
if [[ ! -S /run/phone-fprint-auth/daemon.sock ]]; then
    echo "error: /run/phone-fprint-auth/daemon.sock not found after start" >&2
    echo "error: check 'systemctl status fingerkeyd' and 'journalctl -u fingerkeyd'" >&2
    exit 1
fi
echo "verified unix socket /run/phone-fprint-auth/daemon.sock"

echo "== PAM wiring =="
wire_pam_file /etc/pam.d/sudo
wire_pam_file /etc/pam.d/polkit-1

echo
echo "== install complete =="
echo "  daemon:   ${DAEMON_BIN} (running as ${DAEMON_USER})"
echo "  pair cli: ${PAIR_BIN}"
echo "  module:   ${PAM_MODULE}"
echo "  unit:     ${UNIT_DST} (enabled + started)"
echo "  key dir:  ${KEYS_DIR} (${DAEMON_USER} 0755; parent ${KEYS_PARENT} 0755)"
echo "  tls dir:  ${TLS_DIR} (${DAEMON_USER} 0700; cert/key auto-generated by daemon)"
echo "  pam:      /etc/pam.d/sudo + /etc/pam.d/polkit-1 -> ${PAM_LINE} above @include common-auth"
